version: '3.8'

services:
  exchange_scraper:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "bash install.sh --nosudo && bash install_firefox.sh --nosudo && bash run.sh"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - firefox  # Ensures firefox starts first
  
  firefox:
    image: selenium/standalone-firefox
    shm_size: 1g
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"] # Checks if Selenium WebDriver is responsive
      interval: 30s  # Check every 30 seconds
      timeout: 10s  # Timeout after 10 seconds
      retries: 3  # Mark as unhealthy after 3 failures
      start_period: 30s  # Wait 30s before running the first check
